version: '3'
services:
  meet-mate:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://app-de8c8d1c-285f-4b13-8977-7608d27a1fae-do-user-15830165-0.k.db.ondigitalocean.com:25060/test?sslmode=require
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: AVNS_lagwy7qKce2YNYdXCH5
      SPRING_DATA_MONGODB_URI: mongodb://root:pass@mongodb:27017/admin
    networks:
      - mongo-net

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - mongo-net
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8082:8081"
    networks:
      - mongo-net
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  data: {}

networks:
  mongo-net:
    driver: bridge
