#connecting to a database
spring:
  datasource:
    url: jdbc:postgresql://app-de8c8d1c-285f-4b13-8977-7608d27a1fae-do-user-15830165-0.k.db.ondigitalocean.com:25060/test?sslmode=require
    username: test
    password: AVNS_lagwy7qKce2YNYdXCH5
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb+srv://doadmin:3sQ24W19i75VItn6@db-mongodb-fra1-59236-b223d7ba.mongo.ondigitalocean.com/admin?tls=true&authSource=admin
      database: admin
      auto-index-creation: true
