#connecting to a database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: pass
      database: test
      port: 27017
      host: localhost
      auto-index-creation: true