#connecting to a database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      #show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      uri: mongodb://root:pass@localhost:27017/admin
      database: test
      auto-index-creation: true